# run: conda env create --file environment.yml
name: speclib
channels:
  - conda-forge
dependencies:
    - python>=3.9
    - jupyter
    - pip
    - boto3
    - pandas==1.3.5
    - numpy==1.21.5
    - pip:
      - ms2pip==3.8.0
      - pre-commit==2.15.0
      - matplotlib==3.5.1